# Generated by Django 4.1.3 on 2022-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
